name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Build Dockerfile.lab
        run: GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c1-8) docker build . --file Dockerfile.lab --tag richardotis/jlab-cloud-pycalphad:$GITHUB_SHA_SHORT
      - name: Push Dockerfile.lab
        run: GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c1-8) docker push richardotis/jlab-cloud-pycalphad:$GITHUB_SHA_SHORT
      - name: Build Dockerfile.hub
        run: GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c1-8) docker build . --file Dockerfile.hub --tag richardotis/jhub-cloud-pycalphad:$GITHUB_SHA_SHORT
      - name: Push Dockerfile.hub
        run: GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c1-8) docker push richardotis/jhub-cloud-pycalphad:$GITHUB_SHA_SHORT
