name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Build Dockerfile.lab
        run: docker build --file Dockerfile.lab --tag richardotis/jlab-cloud-pycalphad:${GITHUB_SHA::8} .
      - name: Push Dockerfile.lab
        run: docker push richardotis/jlab-cloud-pycalphad:${GITHUB_SHA::8}
      - name: Build Dockerfile.hub
        run: docker build --file Dockerfile.hub --tag richardotis/jhub-cloud-pycalphad:${GITHUB_SHA::8} .
      - name: Push Dockerfile.hub
        run: docker push richardotis/jhub-cloud-pycalphad:${GITHUB_SHA::8}
